version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "tasks:1:1,worker:1:1,heartbeat:1:1"
    depends_on:
      - zookeeper

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  worker:
    build: .
    command: python -u worker.py
    depends_on:
      - kafka
      - redis
    environment:
      - COORDINATOR_IP=0.0.0.0

  client:
    build: .
    command: python -u yadtq.py
    depends_on:
      - kafka
      - redis
    environment:
      - COORDINATOR_IP=0.0.0.0
